services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  web:
    build: .
    command: bash -c "bin/rails db:prepare && bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      selenium:
          condition: service_started
      elasticsearch:
        condition: service_started
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_ENABLED: "true"
    volumes:
      - .:/app

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      selenium:
            condition: service_started
      elasticsearch:
        condition: service_started
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/0
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_ENABLED: "true"
    volumes:
      - .:/app
  
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: "2gb"

  elasticsearch:
    image: elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      retries: 10

volumes:
  mysql_data:
  redis_data:
